[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha2"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha2"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha2"

[[dependency]]
org = "ballerina"
name = "cache"
version = "2.1.0-alpha2"

[[dependency]]
org = "ballerina"
name = "time"
version = "1.1.0-alpha2"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "0.10.0-alpha2"

[[dependency]]
org = "ballerina"
name = "task"
version = "1.2.0-alpha2"
